name: rtmp_with_capture
description: During RTMP streaming, enable capturing images for a certain task.
publish_to:
version: 0.0.4
homepage: https://github.com/espanic/rtmp_with_capture
environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0




flutter:
  plugin:
    platforms:
      android:
        package: com.example.rtmp_with_capture
        pluginClass: RtmpWithCapturePlugin
      ios:
        pluginClass: RtmpWithCapturePlugin
